### ISSUE TITLE
Stop run tudorial part 1

### ISSUE THREAD

**Issue by ligarius** [tudorelu/tudorials#14]
Hi, 

I run code for tutorial part 1, but just work for one time, then never Works again
Works once for a model.getData() and doesn't run again
Works once for a model.strategy() and doesn't run again

the code is copy/pasted from GitHub, I try to run it in jupyter notebook, but the result is the same 

:-(

**Comment by ligarius** [comment]
seems plotly doesn't print the instance on web, print works ok in df terminal

**Comment by tudorelu** [comment]
Hi @ligarius
 
First of all thank you for the sponsorship! I really appreciate it.

Secondly, this has not been tested in Jupyter. I don't use it myself so I can't know for sure what is wrong, but I can imagine that this would not work well in a web environment.

**Comment by ligarius** [comment]
Hi  @tudorelu, I tested on terminal **and** jupyter,  the most inexplicable thing, is that your code works the first time only, now I copypaste in a new file and the code  doesn't show anything 👎

**Comment by ligarius** [comment]
Find the problem, was a misstyped and when I run your code use model.strategy and no plotData first video
Thanks
close
