### ISSUE TITLE
Censor info.

### ISSUE THREAD

**Issue by thewhitfield** [tudorelu/tudorials#3]
Hey Tudor,

First, amazing work! Thanks so much for taking the time to walk through this project. I've been following on Youtube, I'm really looking forward to video 4, hope it will be soon!

I just wanted to raise an issue on your tudorials/trading/Part 3/Final Version/Binance.py file you have here on GitHub. Please could you review lines 10 and 11? I don't think you want that visible right?

Anyway, keep it up mate! As I said, can't wait for vid 4.

Cheers,

Adam.

**Comment by tudorelu** [comment]
Hey Adam, 

Thank you! Glad I can be of service :) 
Hahaha thanks a bunch for that! The API key is disabled from Binance now. 
Video 4 coming soon, for sure.

Cheers!
